# Generated by Django 2.1.5 on 2019-02-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_album_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='picture',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to=''),
        ),
    ]
